package pi.vortex.rescuethestray.entities;

public enum TypeLRInterest {
    EDUCATION,FUN,GENERAL_KNOWLEDGE,SMALL_PETS, WILDLIFE ,CONSERVATION,PET_TRAINING,PET_BEHAVIOR,PET_GROOMING,
    PET_HEALTH_AND_WELLNESS,
    PET_PRODUCTS_AND_ACCESSORIES,
    PET_INSURANCE,
    ANIMAL_RIGHTS_AND_WELFARE,
    VETERINARY_MEDICINE,
    ANIMAL_PSYCHOLOGY
}
